name: Go Multi-Platform Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install dependencies for macOS
      if: matrix.os == 'macos-latest'
      run: |
        brew install gtk+3 webkit2gtk

    - name: Install dependencies for Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev

    - name: Build for ${{ matrix.os }}
      run: |
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          GOOS=windows GOARCH=amd64 CGO_ENABLED=1 go build -o ./dist/windows/interrupted.exe -ldflags="-H windowsgui -w" ./src/main.go
        elif [ "${{ matrix.os }}" == "macos-latest" ]; then
          GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -o ./dist/macos/interrupted ./src/main.go
        else
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o ./dist/linux/interrupted ./src/main.go
        fi

    - name: Upload release assets
      uses: actions/upload-artifact@v4
      with:
        name: interrupted-${{ matrix.os }}
        path: |
          ./dist/windows/interrupted.exe
          ./dist/macos/interrupted
          ./dist/linux/interrupted

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Test
      run: go test -v ./...