project_name: interrupted
builds:
  - id: windows_build
    goos: windows
    goarch: amd64
    binary: interrupted.exe
    main: ./src/main.go
    ldflags: '-H windowsgui -w'
    output: ./dist/windows/interrupted.exe
    env:
      - CGO_ENABLED=1
    flags:
      - '-o'
      - 'interrupted.exe'
    artifacts:
      - name: "interrupted_windows"
        path: ./dist/windows/interrupted.exe
  - id: macos_build
    goos: darwin
    goarch: amd64
    binary: interrupted
    main: ./src/main.go
    ldflags: ''
    output: ./dist/macos/interrupted
    env:
      - CGO_ENABLED=0
    artifacts:
      - name: "interrupted_macos"
        path: ./dist/macos/interrupted
  - id: linux_build
    goos: linux
    goarch: amd64
    binary: interrupted
    main: ./src/main.go
    ldflags: ''
    output: ./dist/linux/interrupted
    env:
      - CGO_ENABLED=0
    artifacts:
      - name: "interrupted_linux"
        path: ./dist/linux/interrupted
