name: SLSA Go releaser
on:
  workflow_dispatch:
  release:
    types: [created]

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # To sign.
      contents: write # To upload release assets.
      actions: read   # To read workflow path.
    strategy:
      matrix:
        os: [windows, macos, linux]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build for ${{ matrix.os }}
        run: |
          if [ "${{ matrix.os }}" == "windows" ]; then
            go build -o interrupted.exe -ldflags="-H windowsgui -w" src/main.go src/resources.go
          elif [ "${{ matrix.os }}" == "macos" ]; then
            go build -o interrupted src/main.go
          else
            go build -o interrupted src/main.go
          fi
        shell: bash

      - name: Upload release assets
        uses: actions/upload-artifact@v2
        with:
          name: interrupted-${{ matrix.os }}
          path: |
            interrupted.exe
            interrupted
